config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'profile', to: 'pages#profile'
  get 'getstarted', to: 'pages#getstarted'
  get 'mystyle', to: 'pages#mystyle'
  get '/orders/:id/mark_as_shipped',  to: 'orders#mark_as_shipped', as: 'mark_as_shipped'
  post '/favorite_artworks/:id',  to: 'favorite_artworks#like_unlike', as: 'like_unlike'

  # resources :category, only: [:index]
  # need to check everything we need as routes

  # add param :name for renaming the path #param: :username

  resources :categories, only: :show, param: :name

  resources :artists, only: [ :show, :index ] do
    resources :artworks, except: [ :index ]
  end

  resources :orders, only: [:create, :show] do
    resources :payments, only: :new
  end
  resources :favorite_artworks, only: [:new, :create, :destroy]
  resources :artworks, only: [ :index ]


end

app/models/artist.rb
class Artist < ApplicationRecord
  has_one :user, as: :account
  has_many :artworks, dependent: :destroy
  has_many :orders, through: :artworks, dependent: :destroy

  validates :location, presence: true
  validates :vita, presence: true
  validates :nationality, presence: true

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :onboarding
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @artists = Artist.all
  end

  def show
    if User.find_by_username(params[:id]).artist?
      @artist = User.find_by_username(params[:id]).account
    else
      redirect_to "request.referer"
    end
  end
end

app/views/artists/index.html.erb
<div class="artworks-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url('<%= image_path('banner_3_home.jpg') %>')">
  <h1 class="artworks-banner-title">Discover our artists.</h1>
</div>

<div class="background-container">
  <div class="content">
    <div class="container">
      <div class="d-flex flex-wrap align-items-start">
        <% @artists.each do |artist| %>
          <%= link_to artist_path(artist.user.username), style: 'text-decoration: none' do %>
            <div class="account-collector">
              <div class="account-picture">
                <% if artist.user.photo.attached? %>
                  <%= cl_image_tag artist.user.photo.key, :transformation=>[
  {:width=>400, :height=>400, :gravity=>"face", :radius=>"max", :crop=>"crop"},
  {:width=>200, :crop=>"scale"}]%>
                <% else %>
                  <img src='https://www.pphfoundation.ca/wp-content/uploads/2018/05/default-avatar.png'>
                <% end %>
              </div>
              <div class="account-content">
                <h3 class="name"><%= artist.user.first_name %> <%= artist.user.last_name %></h3>
                <h4 class="title">@<%= artist.user.username %></h4>
              </div>
              <div class="edit-btn">
                <h4><%= artist.location %></h4>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/artists/show.html.erb
<div class="background-container">
  <div class="container">
    <div class="row justify-content-between">
      <div class="col-md-4 col-sm-10">
        <div class="d-flex flex-column artist-title">
          <h2> <strong> <%= @artist.user.username.upcase%></strong> </h2>
          <div class="image-wrap d-flex flex-column align-items-center">
            <% if @artist.user.photo.attached? %>
            <%= cl_image_tag @artist.user.photo.key %>
            <% else %>
            <img class="artist-card" src='https://source.unsplash.com/800x450/?people'>
            <% end %>
            <h2>  <%= @artist.user.first_name %> <%= @artist.user.last_name %></h2>
            <h3><i class="fas fa-globe-europe"></i> <%= @artist.location.upcase %></h3>
            <h3> <i class="fas fa-graduation-cap"></i><%= @artist.artschool %></h3>
          </div>
        </div>
        <p></p>
        <div class="box center-btn">
          <a href="#" class="follow-btn follow-btn-white follow-btn-animation-1"> Follow me <i class="fas fa-user-plus"></i></a>
        </div>
        <p></p>
        <div class="card artist-info">
         <h3> STATS </h3>
         <h4><%= pluralize rand(1..20), "Artwork" %> </h4>
         <h4><%= pluralize rand(1..500), "Follow" %> </h4>
         <h4><%= pluralize rand(1..200), "Like" %> </h4>
       </div>
       <br>
       <p>
       </div>
       <div class="col-md-8 col-sm-10">
        <div class="card artist-info">
          <h3> ABOUT ME </h3>
            <pre class="text-display">
              <p> <%= @artist.vita %></p>
            </pre>
        </div>
        <p>
          <div class="container">
            <h3 class="center-btn"> MY ARTWORKS </h3>
            <div class="row">
              <div class="card-container d-flex flex-wrap">
                <div class="d-flex flex-wrap">
                  <% @artist.artworks.each do |artwork| %>
                  <%= render "artworks/card", artwork: artwork %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>