config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'profile', to: 'pages#profile'
  get 'getstarted', to: 'pages#getstarted'
  get 'mystyle', to: 'pages#mystyle'
  get '/orders/:id/mark_as_shipped',  to: 'orders#mark_as_shipped', as: 'mark_as_shipped'
  post '/favorite_artworks/:id',  to: 'favorite_artworks#like_unlike', as: 'like_unlike'

  # resources :category, only: [:index]
  # need to check everything we need as routes

  # add param :name for renaming the path #param: :username

  resources :categories, only: :show, param: :name

  resources :artists, only: [ :show, :index ] do
    resources :artworks, except: [ :index ]
  end

  resources :orders, only: [:create, :show] do
    resources :payments, only: :new
  end
  resources :favorite_artworks, only: [:new, :create, :destroy]
  resources :artworks, only: [ :index ]


end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <!-- Site footer -->
    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <h6>About</h6>
            <p class="text-justify">Coolart <i> makes art</i> accessible from your livingroom.</p>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Categories</h6>
            <ul class="footer-links">
              <li><a href="#">Buy Art</a></li>
              <li><a href="/artists">Artist</a></li>
              <li><a href="#">Art Consutant</a></li>
              <li><a href="#">Career</a></li>
            </ul>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Quick Links</h6>
            <ul class="footer-links">
              <li><a href="#">About Us</a></li>
              <li><a href="#">Contact Us</a></li>
              <li><a href="#">Privacy Policy</a></li>
              <li><a href="#">Sitemap</a></li>
            </ul>
          </div>
        </div>
        <hr>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">This is a non-commercial website, for educational purposes. Copyright &copy; 2020. All Rights Reserved by
         <a href="#">Coolart</a>.
            </p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="www.facebook.com"><i class="fab fa-facebook"></i></a></li>
              <li><a class="twitter" href="www.twitter.com"><i class="fab fa-twitter"></i></a></li>
              <li><a class="dribbble" href="mailto:support@coolart.be?subject=Request%20for%20information%20-%20Coolart&body=Please%20if%20your%20information%20is%20about%20an%20order%2C%20thanks%20to%20provide%20the%20reference%20number"><i class="fas fa-at"></i></a></li>
              <li><a class="linkedin" href="www.linkedin.com"><i class="fab fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-coolart fixed-top">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div>
    <%= link_to root_path do %>
      <img class="navbar-logo" src="/assets/logo-navbar.png">
    <% end %>
  </div>
  <div class="navbar-left btn-cont">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item btn btn-succes">
          <%= link_to "Home", root_path, class:"nav-link hp-btn" %>
          <span class='line-1'></span>
          <span class='line-2'></span>
          <span class='line-3'></span>
          <span class='line-4'></span>
        </li>
        <li class="nav-item link-effect btn btn-succes dropdown">
          <a class="nav-link hp-btn" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Category </a>
            <span class='line-1'></span>
            <span class='line-2'></span>
            <span class='line-3'></span>
            <span class='line-4'></span>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% Category.all.each do |category| %>
                <%= link_to category.name, category_path(category.name), class:"dropdown-item"%>
              <% end %>
            </div>
        </li>
        <li class="nav-item btn btn-succes">
          <%= link_to "Artists", artists_path, class:"nav-link hp-btn" %>
          <span class='line-1'></span>
          <span class='line-2'></span>
          <span class='line-3'></span>
          <span class='line-4'></span>
        </li>
          <li class="nav-item btn btn-succes">
            <%= link_to "Artworks", artworks_path, class:"nav-link hp-btn" %>
            <span class='line-1'></span>
            <span class='line-2'></span>
            <span class='line-3'></span>
            <span class='line-4'></span>
          </li>
          <% if user_signed_in? %>
            <% unless current_user.artist? %>
              <li class="nav-item  link-effect btn btn-succes">
                <%= link_to "Find Your Style", mystyle_path, class:"nav-link hp-btn" %>
                <span class='line-1'></span>
                <span class='line-2'></span>
                <span class='line-3'></span>
                <span class='line-4'></span>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>


    <% if user_signed_in? %>
      <div class="navbar-right">
        <ul class="navbar-nav mr-auto btn-cont">
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src=
            <% if current_user.photo.attached? %>
            <%= cl_image_path current_user.photo.key, :transformation=>[
  {:width=>400, :height=>400, :gravity=>"face", :radius=>"max", :crop=>"crop"},
  {:width=>200, :crop=>"scale"}] %>
            <% else %>
            'https://www.pphfoundation.ca/wp-content/uploads/2018/05/default-avatar.png'
            <% end %> />
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", profile_path, class:"dropdown-item" %>
              <%= link_to "Sign out", destroy_user_session_path, method:"delete", class:"dropdown-item" %>
            </div>
          </li>
        </ul>
      </div>
    <% else  %>
      <div class="navbar-right">
        <ul class="navbar-nav mr-auto btn-cont">
          <li class="nav-item dropdown btn btn-succes">
            <%= link_to "Login", new_user_session_path, class:"nav-link hp-btn" %>
          </li>
        </ul>
      </div>
    <% end %>
 </div>