config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'profile', to: 'pages#profile'
  get 'getstarted', to: 'pages#getstarted'
  get 'mystyle', to: 'pages#mystyle'
  get '/orders/:id/mark_as_shipped',  to: 'orders#mark_as_shipped', as: 'mark_as_shipped'
  post '/favorite_artworks/:id',  to: 'favorite_artworks#like_unlike', as: 'like_unlike'

  # resources :category, only: [:index]
  # need to check everything we need as routes

  # add param :name for renaming the path #param: :username

  resources :categories, only: :show, param: :name

  resources :artists, only: [ :show, :index ] do
    resources :artworks, except: [ :index ]
  end

  resources :orders, only: [:create, :show] do
    resources :payments, only: :new
  end
  resources :favorite_artworks, only: [:new, :create, :destroy]
  resources :artworks, only: [ :index ]


end

app/models/favorite_artwork.rb
class FavoriteArtwork < ApplicationRecord
  belongs_to :artwork
  belongs_to :collector
end

app/controllers/favorite_artworks_controller.rb
class FavoriteArtworksController < ApplicationController
  def like_unlike
    @artwork = Artwork.find(params[:id])
    collector_id = current_user.account.id
    @fav_artwork = FavoriteArtwork.find_by(collector_id: collector_id, artwork: @artwork)
    if @fav_artwork
      @fav_artwork.destroy
    else
      @fav_artwork = FavoriteArtwork.create(collector_id: collector_id, artwork: @artwork)
    end
  end

  def create
    collector_id = current_user.account.id
    @artwork = Artwork.find(params[:artwork_id])
    @fav_artwork = FavoriteArtwork.find_or_create_by(collector_id: collector_id, artwork: @artwork)
    respond_to do |format|
      if @fav_artwork.save!
        format.html
        format.js
      else
        #display alert
        format.html
      end
    end
  end

  def destroy
    @fav_artwork = FavoriteArtwork.find(params[:id])
    @fav_artwork.destroy
  end

  private

  def fav_artworks_params
    params.require(:favorite_artwork).permit(:artwork_id)
  end

end

app/views/favorite_artworks/_created_like.html.erb
<%= link_to favorite_artworks_path(artwork_id: @artwork.id), remote: true, method: 'post' do %>
  <i class="far fa-heart"></i>
<% end %>

app/views/favorite_artworks/_destroy_like.html.erb
<%= link_to favorite_artwork_path(@fav_artwork), remote: true, method: 'delete' do %>
  <i class="fas fa-heart"></i>
<% end %>

app/views/favorite_artworks/create.js.erb
console.log('hello');

if (document.getElementById('artlike'))
{document.getElementById('artlike').innerHTML = "<%= j render 'created_like' %>"};

if (document.getElementById('checkbox-<%=@fav_artwork.artwork_id %>'))
{document.getElementById('checkbox-<%=@fav_artwork.artwork_id %>').checked = true};

app/views/favorite_artworks/destroy.js.erb
console.log('hello')

document.getElementById('artlike').innerHTML = "<%= j render 'destroy_like' %>"

app/views/favorite_artworks/like_unlike.js.erb
var heartCheckbox = document.getElementById('checkbox-<%=@fav_artwork.artwork_id %>');


if (heartCheckbox)
{heartCheckbox.checked = !heartCheckbox.checked};

var row = document.querySelector("#recommendations-container");
if (row) {
row.innerHTML = ""
row.insertAdjacentHTML('afterbegin',
  `<div class="row"><div class="col-12"><h2>You might also like...</h2><div class="card-container d-flex flex-wrap"><div class="p-2 d-flex flex-wrap align-content-start"><% @artwork.similar_items(n_results: 3).each do |artwork| %><%= render "artworks/card", artwork: artwork %><% end %></div></div></div></div>` )
};