config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get 'profile', to: 'pages#profile'
  get 'getstarted', to: 'pages#getstarted'
  get 'mystyle', to: 'pages#mystyle'
  get '/orders/:id/mark_as_shipped',  to: 'orders#mark_as_shipped', as: 'mark_as_shipped'
  post '/favorite_artworks/:id',  to: 'favorite_artworks#like_unlike', as: 'like_unlike'

  # resources :category, only: [:index]
  # need to check everything we need as routes

  # add param :name for renaming the path #param: :username

  resources :categories, only: :show, param: :name

  resources :artists, only: [ :show, :index ] do
    resources :artworks, except: [ :index ]
  end

  resources :orders, only: [:create, :show] do
    resources :payments, only: :new
  end
  resources :favorite_artworks, only: [:new, :create, :destroy]
  resources :artworks, only: [ :index ]


end

app/views/pages/artist_partials/_artworks.html.erb
<div class="d-flex flex-column justify-content-center artworks-artist">
  <div class="d-flex" style="margin-left: 50px; margin-top: 10px">
    <%= link_to "Add artwork", new_artist_artwork_path(current_user.account), class:"add-button" %>
  </div>
  <br>
  <div class="artworks-artist">
    <h2>Active</h2>
  </div>
  <div class="p-2 d-flex flex-wrap align-content-start">
    <% current_user.account.artworks.each do |artwork| %>
      <% if artwork.orders.where(status: [:confirmed, :dispatched, :fulfilled]).size < 1  %>
        <%= render "artworks/card", artwork: artwork %>
      <% end %>
    <% end %>
  </div>
  <div class="artworks-artist">
    <h2>Sold</h2>
  </div>
  <div class="p-2 d-flex flex-wrap align-content-start">
    <% current_user.account.artworks.each do |artwork| %>
      <% if artwork.orders.where(status: [:confirmed, :dispatched, :fulfilled]).size > 0 %>
        <%= render "artworks/card", artwork: artwork %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pages/artist_partials/_my_account.html.erb
<div class="d-flex">
  <div class="account-collector">
    <div class="account-picture">
      <% if current_user.photo.attached? %>
        <%= cl_image_tag current_user.photo.key, :transformation=>[
  {:width=>400, :height=>400, :gravity=>"face", :radius=>"max", :crop=>"crop"},
  {:width=>200, :crop=>"scale"}] %>
      <% else %>
        <img src='https://www.pphfoundation.ca/wp-content/uploads/2018/05/default-avatar.png'>
      <% end %>
    </div>
    <div class="account-content">
      <h3 class="name"><%= current_user.first_name %> <%= current_user.last_name %></h3>
      <h4 class="title">@<%= current_user.username %></h4>
    </div>
    <div class="edit-btn">
      <%= link_to "Update details", edit_user_registration_path %>
    </div>
  </div>
  <div class="account-details">
    <h2><i class="fas fa-map-marker-alt"></i>     <%= current_user.account.location %></h2>
    <h2><i class="fas fa-globe"></i>    <%= current_user.account.nationality %></h2>
    <% if current_user.account.date_of_birth %>
      <h2><i class="fas fa-birthday-cake"></i>    <%= current_user.account.date_of_birth %></h2>
    <% end %>
    <% if current_user.account.artschool %>
      <h2><i class="fas fa-graduation-cap"></i>    <%= current_user.account.artschool %></h2>
    <% end %>
    <p><%= current_user.account.vita %></p>
  </div>
</div>

app/views/pages/artist_partials/_orders.html.erb
<div class="m-2 d-flex flex-wrap">
  <% current_user.account.orders.each do |order| %>
    <div class="card-order">
    <div class="order-picture">
      <%= cl_image_tag order.artwork.photos.first.key %>
    </div>
    <div class="order-content">
      <h1><%= order.artwork.name %>, <%= order.artwork.year %></h1>
      <h2><%= order.collector.user.first_name %> <%= order.collector.user.last_name %></h2>
      <h3><%= order.artwork.price %> €</h3>
      <% if order.status == 0 %>
        <%= link_to "Mark as shipped", mark_as_shipped_path(order), class:"mark-as-shipped-btn" %>
      <% elsif order.status == 1 %>
        <h4 id="shipped">Shipped</h4>
      <% else %>
        <h4 id="fulfilled">Fulfilled</h4>
      <% end %>
    </div>
  </div>
  <% end %>
</div>